version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klaviyo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mysql://klaviyo_user:klaviyo_password@mysql:3306/klaviyo_backend
      - KLAVIYO_API_KEY=${KLAVIYO_API_KEY}
      - KLAVIYO_BASE_URL=https://a.klaviyo.com/api
      - DATA_RETENTION_DAYS=7
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - klaviyo-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: klaviyo-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=klaviyo_backend
      - MYSQL_USER=klaviyo_user
      - MYSQL_PASSWORD=klaviyo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - klaviyo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "klaviyo_user", "-pklaviyo_password"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: klaviyo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - klaviyo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: klaviyo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - klaviyo-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  klaviyo-network:
    driver: bridge